# This is a basic workflow to help you get started with Actions

name: CI155

# Controls when the workflow will run
on: [push]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v1
     - name: Create SSH key
       uses:  aminedev124/githubaction@main
       with:
          hosts: 'ec2-18-118-115-218.us-east-2.compute.amazonaws.com'
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: mkdir /amine
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
